"""Stage 7 — Reels: propose ~20 short-form candidates from the kept content,
scored by the local LLM on the transcript (hook / clarity / payoff). Rendering
a candidate crops to 9:16 centered on the speaker's face and burns subtitles
built from whisper word timestamps.

Reel Editor overrides (spec v5): each reel may carry in_override/out_override
(clip-local seconds, may extend beyond the AI window, clamped to clip
bounds), crop_x (0..1 horizontal center, bypasses face detection),
cue_overrides ({cue_index: text}), subtitle_style (partial override merged
over project["subtitles"]), and editable title/description.

Multi-segment reels (spec v5.8b "the podcast case"): a reel is no longer
always a single continuous window. reel["segments"] = [{clip_id, start, end,
in_override, out_override}] (same override shape as before, now per segment)
and reel["transitions"] = junction transitions between consecutive segments
(one fewer than len(segments), default crossfade 0.4s). A pre-v5.8b
single-window reel is migrated to a 1-segment list (with no transitions) the
first time `ensure_segments` sees it (called from render_reel and from
api/reels.py). The legacy top-level clip_id/start/end/in_override/
out_override fields are kept in sync with segment 0 by `_sync_legacy_fields`
so the current (single-window) Reel Editor frontend keeps working unmodified
-- it only ever reads/writes segment 0 until it grows multi-segment UI.
cue_overrides indices are GLOBAL across the reel's segments concatenated in
order (index 0 is the first cue of segment 0, continuing into segment 1,
...), both for the /cues endpoint and for render_reel's per-segment .ass
burn-in (see `_segment_cue_overrides`). crop_x/face-detection is resolved
ONCE (from segment 0, unless crop_x is set) and reused for every segment's
crop filter -- only the per-clip pixel geometry differs (spec: "face-crop
computed on the FIRST segment unless crop_x set").

Viral composer pass (spec v5.8b "the podcast case"): after the single-window
reel_scorer pass, `_run_composer_pass` looks for PAIRS of high-scoring
windows that continue the same idea apart in time (setup+payoff,
question+answer, ...) among the top ~15 scored windows, pre-filtered by
rapidfuzz keyword overlap and capped at ~10 agent calls (task
'reel_composer'). A pair the agent says to `combine` becomes a 2-segment
candidate with a +2 score bonus, entering the same top-N / overlap-limited
pick loop as single-window candidates (see `_windows_of`/`_overlap`, which
treat both uniformly); reels built from a combined pair are flagged
reel["composed"] = True with reel["composer_why"] set to the agent's
rationale.

Render (reels.render_reel): reuses render.py's per-segment encode
(`render._encode_segment`) and junction crossfade merge
(`render._merge_crossfades`) rather than reimplementing them -- see that
module's docstring for the junction algorithm. Each segment is cut/cropped/
subtitled independently (crop/subs/overrides apply per segment; face-crop
computed once as above), then junctions are merged exactly like the main
render, then concatenated.

Export naming (spec v5 addendum): rendered reels are written straight to
settings.export_dir/<project name>/<sanitized reel title>.mp4 (falling back
to "Reel <rank>" when there's no title yet), deduped against what's already
there ("<stem> (2).mp4", ...). Internal work files (the per-reel .ass/.wav
under <project>/work) keep using the reel id; only the final artifact adopts
the title-based name, and reel["path"] is updated to point at it.

Copywriter integration (spec v5 addendum): after picking the top N, each
reel's title/description/hashtags are generated by the COPYWRITER agent
(magic_video_editor/pipeline/copywriter.py, a parallel deliverable) via copy_for_reel —
imported lazily so this module works whether or not that file has landed
yet. On success it replaces reel_scorer's title; on failure/absence the
scorer's title is kept as a fallback."""

import re
import time
import uuid
from pathlib import Path

from rapidfuzz import fuzz

from .. import config, ffmpeg_utils, llm, settings, store
from ..agents.agents import get_agent
from . import audio_enhance, faces, filters, subtitles
from . import render as render_mod

DEFAULT_TRANSITION = {"type": "crossfade", "duration": 0.4}

# Fit mode (spec v7.7 "Zoom out con fondo blur"): "fill" (default, current
# face-centered 9:16 crop behavior, unchanged) vs "fit_blur" (background =
# same video scaled to fill + blurred/darkened, foreground = video scaled to
# fit_scale centered -- the classic vertical-video treatment, and the
# one-click fix a safety-zone warning offers). Range/default match
# pipeline/safezones.py's FIT_SCALE_MIN/MAX (0.6..1.0) exactly, since that
# module computes `suggested_fit_scale` values in this same range.
DEFAULT_FIT_MODE = "fill"
DEFAULT_FIT_SCALE = 0.82
FIT_SCALE_MIN = 0.6
FIT_SCALE_MAX = 1.0
_COMPOSER_TOP_WINDOWS = 15
_COMPOSER_MAX_PAIR_CALLS = 10
_COMPOSER_MIN_GAP_S = 3.0
_COMPOSER_SCORE_BONUS = 2.0


def _candidate_windows(project: dict) -> list[dict]:
    """Sliding windows of consecutive kept sentences within one clip,
    bounded to REEL_MIN_S..REEL_MAX_S."""
    out = []
    for clip in project["clips"]:
        if clip["role"] != "camera":
            continue
        sents = sorted(
            (s for s in project["sentences"] if s["clip_id"] == clip["id"] and s["kept"]),
            key=lambda s: s["start"],
        )
        for i in range(len(sents)):
            acc, texts = [], []
            for j in range(i, len(sents)):
                if acc and sents[j]["start"] - acc[-1]["end"] > 4.0:
                    break  # big content hole — not one continuous thought
                acc.append(sents[j])
                texts.append(sents[j]["text"])
                dur = acc[-1]["end"] - acc[0]["start"]
                if dur > config.REEL_MAX_S:
                    break
                if dur >= config.REEL_MIN_S:
                    out.append(
                        {
                            "clip_id": clip["id"],
                            "start": acc[0]["start"],
                            "end": acc[-1]["end"],
                            "text": " ".join(texts),
                            "duration": round(dur, 1),
                        }
                    )
                    if dur >= config.REEL_MAX_S * 0.75:
                        break
    # thin out: keep at most ~80 for the LLM pass, longest-first per start point
    seen, thinned = set(), []
    for c in sorted(out, key=lambda c: (c["clip_id"], c["start"], -c["duration"])):
        key = (c["clip_id"], round(c["start"] / 5))
        if key in seen:
            continue
        seen.add(key)
        thinned.append(c)
    return thinned[:80]


def _windows_of(c: dict) -> list[dict]:
    """The one or more {clip_id, start, end} windows a scored candidate
    covers -- plain single-window candidates have exactly one (themselves);
    composer-combined candidates carry the pair in `segments_data`. Letting
    `_overlap` go through this makes the top-N/overlap-limited pick loop
    treat singles and composed pairs uniformly."""
    return c.get("segments_data") or [
        {"clip_id": c["clip_id"], "start": c["start"], "end": c["end"]}
    ]


def _overlap(a: dict, b: dict) -> float:
    """Max pairwise overlap ratio between any of a's windows and any of b's
    windows on the SAME clip (0 for windows on different clips)."""
    max_ov = 0.0
    for wa in _windows_of(a):
        for wb in _windows_of(b):
            if wa["clip_id"] != wb["clip_id"]:
                continue
            inter = min(wa["end"], wb["end"]) - max(wa["start"], wb["start"])
            union = max(wa["end"], wb["end"]) - min(wa["start"], wb["start"])
            if union > 0:
                max_ov = max(max_ov, max(0.0, inter) / union)
    return max_ov


def _composer_candidate_pairs(scored: list[dict]) -> list[tuple[dict, dict]]:
    """Candidate pairs for the viral composer pass: among the top ~15 scored
    windows, pre-filter by rapidfuzz keyword overlap (proxy for "same idea
    continued") and cap at ~10 agent calls (spec v5.8b). Same-clip pairs
    must not overlap and must be separated by a minimum gap -- "separated in
    time" per spec, not two overlapping/adjacent picks of the same moment."""
    top = scored[:_COMPOSER_TOP_WINDOWS]
    ranked = []
    for i in range(len(top)):
        for j in range(i + 1, len(top)):
            a, b = top[i], top[j]
            if a["clip_id"] == b["clip_id"]:
                gap = max(a["start"], b["start"]) - min(a["end"], b["end"])
                if _overlap(a, b) > 0 or gap < _COMPOSER_MIN_GAP_S:
                    continue
            sim = fuzz.token_set_ratio(a["text"], b["text"])
            ranked.append((sim, a, b))
    ranked.sort(key=lambda t: -t[0])
    return [(a, b) for _, a, b in ranked[:_COMPOSER_MAX_PAIR_CALLS]]


def _run_composer_pass(log, scored: list[dict]) -> list[dict]:
    """Runs the 'reel_composer' agent over each pre-filtered candidate pair;
    pairs the agent says to combine become 2-segment pseudo-candidates (with
    the same score/hook/self_contained/payoff/title/text shape as a plain
    scored window, plus segments_data/composed/composer_why) that get folded
    back into the ranking pool by the caller."""
    pairs = _composer_candidate_pairs(scored)
    if not pairs:
        return []
    composer_agent = get_agent("reel_composer")
    combined = []
    for a, b in pairs:
        prompt = (
            f'Window A ({a["duration"]}s):\n"{a["text"][:800]}"\n\n'
            f'Window B ({b["duration"]}s):\n"{b["text"][:800]}"'
        )
        try:
            r = composer_agent.run_sync(prompt).output
        except Exception as e:
            log(f"composer pair error, skipping ({e})")
            continue
        if not r.combine:
            continue
        ordered = [a, b] if r.order == "ab" else [b, a]
        best = max(ordered, key=lambda w: w["score"])
        combined.append(
            {
                "clip_id": ordered[0]["clip_id"],
                "start": ordered[0]["start"],
                "end": ordered[0]["end"],
                "duration": round(sum(w["duration"] for w in ordered), 1),
                "title": best.get("title", ""),
                "hook": max(w["hook"] for w in ordered),
                "self_contained": max(w["self_contained"] for w in ordered),
                "payoff": max(w["payoff"] for w in ordered),
                "score": round(max(w["score"] for w in ordered) + _COMPOSER_SCORE_BONUS, 1),
                "text": f'{ordered[0]["text"]} [...] {ordered[1]["text"]}',
                "segments_data": [
                    {"clip_id": w["clip_id"], "start": w["start"], "end": w["end"]}
                    for w in ordered
                ],
                "composed": True,
                "composer_why": r.why,
            }
        )
        log(f"Composer: combining 2 windows (order={r.order}) — {r.why}")
    return combined


def _hashtags_list(value) -> list[str]:
    """Normalize the copywriter's `hashtags` output into a list of tag
    strings. copywriter.py's CopywriterOutput.hashtags is a single
    space-separated string (e.g. "#Foo #Bar") by schema/spec (flat,
    small-model-friendly output) -- naively doing list(value) on a string
    explodes it character-by-character (real bug found on project
    c7642fc7755e's reel b0996e24: hashtags == ['#','R','u',...]). Split on
    whitespace instead; tolerate a real list/tuple too in case the
    copywriter contract ever changes."""
    if not value:
        return []
    if isinstance(value, str):
        return [t for t in value.split() if t.strip()]
    return [str(t) for t in value if str(t).strip()]


def _copy_for_reel_safe(project: dict, reel: dict) -> dict | None:
    """copy_for_reel(project, reel) -> {"title","description","hashtags"},
    or None if the copywriter module isn't available yet (ImportError, a
    parallel deliverable) or it errored on this reel — callers fall back to
    keeping whatever title/description the reel already has."""
    try:
        from .copywriter import copy_for_reel
    except ImportError:
        return None
    try:
        return copy_for_reel(project, reel)
    except Exception:
        return None


def suggest(log, project: dict) -> None:
    if not project.get("sentences"):
        raise RuntimeError("Run Take analysis first.")
    if not llm.available():
        raise RuntimeError("Ollama is not running — reel scoring needs the local LLM.")

    candidates = _candidate_windows(project)
    if not candidates:
        raise RuntimeError("No candidate windows (need >=15s of continuous kept speech).")
    reel_scorer_agent = get_agent("reel_scorer")
    log(f"Scoring {len(candidates)} candidate windows...")

    scored = []
    for ci, cand in enumerate(candidates):
        prompt = f'Candidate window ({cand["duration"]}s):\n"{cand["text"][:1200]}"'
        try:
            s = reel_scorer_agent.run_sync(prompt).output
            c = dict(cand)
            c["hook"] = float(s.hook)
            c["self_contained"] = float(s.self_contained)
            c["payoff"] = float(s.payoff)
            c["title"] = s.title[:80]
            c["score"] = round(c["hook"] * 1.4 + c["self_contained"] + c["payoff"], 1)
            scored.append(c)
        except Exception as e:
            log(f"candidate {ci}: LLM error, skipping ({e})")
        log.progress(min(0.95, (ci + 1) / len(candidates)))

    # Viral composer pass (spec v5.8b): look for pairs of scored windows that
    # continue the same idea apart in time; combined candidates get a +2
    # bonus and compete in the same top-N pick below.
    scored.sort(key=lambda c: -c["score"])
    composed_candidates: list[dict] = []
    if len(scored) >= 2:
        log("Looking for composable viral pairs...")
        try:
            composed_candidates = _run_composer_pass(log, scored)
        except Exception as e:
            log(f"composer pass error, skipping ({e})")
    if composed_candidates:
        log(f"Composer combined {len(composed_candidates)} pair(s).")

    # top N with limited mutual overlap (singles + composed pairs uniformly)
    all_candidates = sorted(scored + composed_candidates, key=lambda c: -c["score"])
    picked = []
    for c in all_candidates:
        if all(_overlap(c, p) < 0.45 for p in picked):
            picked.append(c)
        if len(picked) >= config.REEL_SUGGESTIONS:
            break

    project["reels"] = []
    for i, c in enumerate(picked):
        composed = bool(c.get("composed"))
        if composed:
            segments = [
                {
                    "clip_id": w["clip_id"],
                    "start": w["start"],
                    "end": w["end"],
                    "in_override": None,
                    "out_override": None,
                }
                for w in c["segments_data"]
            ]
            transitions = [dict(DEFAULT_TRANSITION)]
        else:
            segments = [
                {
                    "clip_id": c["clip_id"],
                    "start": c["start"],
                    "end": c["end"],
                    "in_override": None,
                    "out_override": None,
                }
            ]
            transitions = []
        reel = {
            "id": uuid.uuid4().hex[:8],
            "rank": i + 1,
            "clip_id": c["clip_id"],
            "start": c["start"],
            "end": c["end"],
            "duration": c["duration"],
            "title": c.get("title", ""),
            "description": "",
            "hashtags": [],
            "score": c["score"],
            "hook": c["hook"],
            "self_contained": c["self_contained"],
            "payoff": c["payoff"],
            "text": c["text"],
            "path": None,
            "status": "suggested",
            # Reel Editor overrides (spec v5) — all optional, unset until a
            # PATCH from the Reel Editor sets one.
            "in_override": None,
            "out_override": None,
            "crop_x": None,
            "cue_overrides": {},
            "subtitle_style": {},
            # Fit mode / safe-zone fix (spec v7.7) — see module constants above.
            "fit_mode": DEFAULT_FIT_MODE,
            "fit_scale": DEFAULT_FIT_SCALE,
            # Multi-segment reels (spec v5.8b) — see module docstring.
            "segments": segments,
            "transitions": transitions,
            "composed": composed,
        }
        if composed:
            reel["composer_why"] = c.get("composer_why", "")
        project["reels"].append(reel)

    log("Writing reel copy (title/description/hashtags)...")
    for reel in project["reels"]:
        copy = _copy_for_reel_safe(project, reel)
        if copy:
            reel["title"] = str(copy.get("title") or reel["title"])[:80]
            reel["description"] = str(copy.get("description") or "")
            reel["hashtags"] = _hashtags_list(copy.get("hashtags"))

    store.save(project)
    n_composed = sum(1 for r in project["reels"] if r.get("composed"))
    log(
        f"Suggested {len(picked)} reels (from {len(scored)} scored candidates, "
        f"{n_composed} composed)."
    )


def regenerate_copy(project: dict, reel: dict) -> dict:
    """Re-run the copywriter for one reel, unconditionally overwriting its
    title/description/hashtags (spec: "Regenerate copy" button — this is the
    one explicit path allowed to replace a manually-edited title; nothing
    else touches it after suggest() seeds it). Raises RuntimeError if the
    copywriter module isn't available or errors."""
    copy = _copy_for_reel_safe(project, reel)
    if not copy:
        raise RuntimeError(
            "Copywriter unavailable — magic_video_editor/pipeline/copywriter.py missing or errored."
        )
    reel["title"] = str(copy.get("title") or reel["title"])[:80]
    reel["description"] = str(copy.get("description") or "")
    reel["hashtags"] = _hashtags_list(copy.get("hashtags"))
    return reel


# ---------- export filename sanitization (spec v5 addendum) ----------
# Kept independently implemented here (rather than importing render.py's
# private sanitization helpers) so filename rules have no load-order/
# edit-conflict coupling to a file owned by a different task; the rules are
# the same by spec, just duplicated. This is unlike the junction/crossfade
# render pipeline below, which the spec explicitly says to reuse from
# render.py (`render_mod._encode_segment`/`_merge_crossfades`).


def _sanitize_title(name: str) -> str:
    """Filename stem: strip /:\\ and control chars, collapse whitespace."""
    cleaned = re.sub(r'[/:\\\x00-\x1f]', "", name or "")
    cleaned = re.sub(r"\s+", " ", cleaned).strip()
    return cleaned


def _safe_folder_name(name: str) -> str:
    cleaned = re.sub(r'[<>:"/\\|?*\x00-\x1f]', "_", name or "").strip()
    return cleaned or "project"


def _unique_export_path(export_dir: Path, stem: str, ext: str = ".mp4") -> Path:
    """Dedupe an export filename against what's already on disk: "<stem>.mp4",
    then "<stem> (2).mp4", "<stem> (3).mp4", ..."""
    candidate = export_dir / f"{stem}{ext}"
    if not candidate.exists():
        return candidate
    n = 2
    while True:
        candidate = export_dir / f"{stem} ({n}){ext}"
        if not candidate.exists():
            return candidate
        n += 1


def _export_dir_for(project: dict) -> Path:
    """settings.export_dir, per-project subfolder (same layout render.py's
    final render uses)."""
    try:
        raw = settings.load().get("export_dir")
    except Exception:
        raw = None
    root = Path(raw).expanduser() if raw else (Path.home() / "Movies" / "Magic Video Editor")
    d = root / _safe_folder_name(project.get("name") or project["id"])
    d.mkdir(parents=True, exist_ok=True)
    return d


def _export_stem_for_reel(reel: dict) -> str:
    stem = _sanitize_title(reel.get("title") or "")
    return stem or f"Reel {reel['rank']}"


# ---------- multi-segment migration (spec v5.8b) ----------


def _normalize_transition(t: dict | None) -> dict:
    """Defensive normalization, mirroring render.py's `_normalize_transition`
    but with a crossfade default (spec v5.8b: "default crossfade 0.4") rather
    than "none", since reel junctions default to crossfade."""
    if not t:
        return dict(DEFAULT_TRANSITION)
    ttype = t.get("type") or "crossfade"
    if ttype not in ("none", "fade", "crossfade"):
        ttype = "crossfade"
    if ttype == "none":
        return {"type": "none", "duration": 0.0}
    duration = float(t.get("duration") or DEFAULT_TRANSITION["duration"])
    duration = min(1.5, max(0.1, duration))
    return {"type": ttype, "duration": duration}


def _normalize_transitions(reel: dict) -> None:
    n_junctions = max(0, len(reel["segments"]) - 1)
    trans = list(reel.get("transitions") or [])[:n_junctions]
    while len(trans) < n_junctions:
        trans.append(dict(DEFAULT_TRANSITION))
    reel["transitions"] = [_normalize_transition(t) for t in trans]


def _sync_legacy_fields(reel: dict) -> None:
    """Keep the pre-v5.8b top-level clip_id/start/end/in_override/
    out_override mirroring segment 0, so the current (single-window) Reel
    Editor frontend keeps working unmodified against multi-segment reels."""
    seg0 = reel["segments"][0]
    reel["clip_id"] = seg0["clip_id"]
    reel["start"] = seg0["start"]
    reel["end"] = seg0["end"]
    reel["in_override"] = seg0.get("in_override")
    reel["out_override"] = seg0.get("out_override")


def _normalize_fit(reel: dict) -> None:
    """Defensive normalization for fit_mode/fit_scale (spec v7.7), mirroring
    the pattern of `_normalize_transition`/`_normalize_transitions` above:
    an unknown/missing fit_mode falls back to "fill", fit_scale is clamped
    to FIT_SCALE_MIN..FIT_SCALE_MAX and only meaningful once fit_mode is
    "fit_blur" (kept/clamped regardless so a mode toggle back to fit_blur
    remembers the last value)."""
    mode = reel.get("fit_mode") or DEFAULT_FIT_MODE
    if mode not in ("fill", "fit_blur"):
        mode = DEFAULT_FIT_MODE
    reel["fit_mode"] = mode
    try:
        scale = float(reel.get("fit_scale") or DEFAULT_FIT_SCALE)
    except (TypeError, ValueError):
        scale = DEFAULT_FIT_SCALE
    reel["fit_scale"] = min(FIT_SCALE_MAX, max(FIT_SCALE_MIN, scale))


def ensure_segments(reel: dict) -> None:
    """Migrate a legacy single-window reel (pre spec v5.8b, no "segments"
    key) to the multi-segment shape IN PLACE: reel["segments"] = [{clip_id,
    start, end, in_override, out_override}] (from the reel's own top-level
    fields), reel["transitions"] = [] (a single segment has no junctions).
    Idempotent -- a no-op (besides re-syncing legacy fields/normalizing
    transitions/fit) once "segments" is already present. Callers: render_reel
    and api/reels.py's `_load_reel`."""
    if not reel.get("segments"):
        reel["segments"] = [
            {
                "clip_id": reel["clip_id"],
                "start": reel["start"],
                "end": reel["end"],
                "in_override": reel.get("in_override"),
                "out_override": reel.get("out_override"),
            }
        ]
    reel.setdefault("transitions", [])
    reel.setdefault("composed", False)
    _normalize_transitions(reel)
    _sync_legacy_fields(reel)
    _normalize_fit(reel)


# ---------- override resolution (spec v5 data model, per segment) ----------


def _effective_segment_window(clip: dict, seg: dict) -> tuple[float, float]:
    """(start, end) honoring seg's in_override/out_override, clamped to the
    clip's own duration (may EXTEND beyond the AI-suggested window, per
    spec). `seg` is either an entry of reel["segments"] or (for the legacy
    single-segment case, since _sync_legacy_fields mirrors segment 0 onto
    the reel dict itself) the reel dict directly -- both have the same
    start/end/in_override/out_override shape."""
    duration = (clip.get("info") or {}).get("duration")
    if not duration or duration <= 0:
        duration = max(seg["end"], seg.get("out_override") or 0.0)

    start = seg.get("in_override")
    start = seg["start"] if start is None else float(start)
    end = seg.get("out_override")
    end = seg["end"] if end is None else float(end)

    start = max(0.0, min(start, duration))
    end = max(start + 0.05, min(end, duration))
    return start, end


def _effective_crop_center(log, clip: dict, reel: dict, start: float, end: float):
    """(x, y) fraction center for the 9:16 crop: an explicit crop_x override
    bypasses face detection entirely (spec); otherwise fall back to
    detecting the speaker's face over the effective window. Called ONCE per
    reel (on segment 0) -- spec v5.8b: "face-crop computed on the FIRST
    segment unless crop_x set" -- and the same fraction is reused for every
    other segment's crop filter."""
    crop_x = reel.get("crop_x")
    if crop_x is not None:
        center = faces.manual_center(crop_x)
        log(f"Using manual crop_x={crop_x} (face detection bypassed)")
        return center
    log("Analyzing frames for speaker position (first segment)...")
    center = faces.face_center(clip["path"], start, end)
    log(f"Face center: {center if center else 'not found — using frame center'}")
    return center


def _effective_subtitle_cfg(project: dict, reel: dict) -> dict:
    """project["subtitles"] normalized, then partially overridden by
    reel["subtitle_style"] (spec: "partial override of project['subtitles']"
    scoped to just this reel -- shared across all of the reel's segments)."""
    base = subtitles.normalize_config(project.get("subtitles"))
    override = reel.get("subtitle_style") or {}
    return subtitles.normalize_config({**base, **override})


def _segment_cue_overrides(
    clip: dict, start: float, end: float, cfg: dict, global_overrides: dict, offset: int
) -> tuple[dict, int]:
    """Re-key the reel's GLOBAL cue_overrides ({global_cue_index: text}, see
    module docstring) down to the LOCAL indices `subtitles.write_ass` expects
    for one segment's own [start,end) window, given `offset` = the number of
    cues already emitted by earlier segments. Returns (local_overrides,
    this_segment's_cue_count) so the caller can advance the offset."""
    cues = subtitles.cues_for_range(clip, start, end, cfg)
    local: dict[int, str] = {}
    if global_overrides:
        for cue in cues:
            gi = cue["index"] + offset
            val = global_overrides.get(gi, global_overrides.get(str(gi)))
            if val is not None:
                local[cue["index"]] = val
    return local, len(cues)


def _fit_blur_vf(width: int, height: int, fit_scale: float) -> str:
    """Classic "zoom out with blurred background" vertical-video treatment
    (spec v7.7): background = the SAME source scaled to FILL the 9:16 frame
    (force_original_aspect_ratio=increase + center crop) with a strong
    boxblur and a slight darken; foreground = the source scaled to fit
    within `fit_scale` of the frame (preserving its own aspect ratio),
    centered on top. Built as one filtergraph string (split -> two labeled
    chains -> overlay) so it slots into `_encode_segment`'s vf_extra exactly
    like the plain crop filter `faces.vertical_crop_filter` returns for the
    default "fill" mode: `_encode_segment` appends its own
    scale=width:height,pad=width:height,fps=... chain right after via a
    plain comma, which becomes a no-op once the overlay output is already
    exactly width x height."""
    fit_scale = min(FIT_SCALE_MAX, max(FIT_SCALE_MIN, fit_scale))
    fg_w = max(2, round(width * fit_scale) // 2 * 2)
    fg_h = max(2, round(height * fit_scale) // 2 * 2)
    return (
        "split=2[fbbg][fbfg];"
        f"[fbbg]scale={width}:{height}:force_original_aspect_ratio=increase,"
        f"crop={width}:{height},boxblur=20:1,eq=brightness=-0.08[fbbgout];"
        f"[fbfg]scale={fg_w}:{fg_h}:force_original_aspect_ratio=decrease[fbfgout];"
        "[fbbgout][fbfgout]overlay=(W-w)/2:(H-h)/2"
    )


def render_reel(log, project: dict, reel_id: str) -> None:
    """Renders every segment of the reel (crop/subs/color/overrides apply
    per segment; face-crop resolved once from segment 0 unless crop_x is
    set), then merges junction transitions and concatenates -- reusing
    render.py's `_encode_segment`/`_merge_crossfades` (see module docstring)
    rather than reimplementing the crossfade/concat pipeline. A 1-segment
    reel takes the exact same path (no transitions -> merge/concat are
    no-ops beyond a straight copy-through), so this is not a special-cased
    fork of the old single-window behavior."""
    reel = next((r for r in project["reels"] if r["id"] == reel_id), None)
    if not reel:
        raise RuntimeError(f"reel {reel_id} not found")
    ensure_segments(reel)
    segments = reel["segments"]

    pdir = store.project_dir(project["id"])
    work = pdir / "work" / f"reel_{reel_id}"
    work.mkdir(parents=True, exist_ok=True)

    fit_mode = reel.get("fit_mode") or DEFAULT_FIT_MODE
    fit_scale = float(reel.get("fit_scale") or DEFAULT_FIT_SCALE)

    first_clip = store.get_clip(project, segments[0]["clip_id"])
    start0, end0 = _effective_segment_window(first_clip, segments[0])
    center = None
    if fit_mode != "fit_blur":
        # fit_blur has no crop -- skip face detection entirely (spec: the
        # background/foreground scale treatment doesn't need a crop center).
        center = _effective_crop_center(log, first_clip, reel, start0, end0)
    log.progress(0.2)

    color_vf = filters.build_vf(project.get("color"))
    sub_cfg = _effective_subtitle_cfg(project, reel)
    burn_subs = ffmpeg_utils.supports_subtitles()
    if not burn_subs:
        log("ffmpeg has no libass — rendering without burned subtitles")
    cue_overrides = reel.get("cue_overrides") or {}
    fps = min(first_clip["info"]["fps"] or 30.0, 60.0)

    # transitions_full[i] is the transition INTO segments[i] (render.py's own
    # convention for _encode_segment's fade args / _merge_crossfades), i.e.
    # transitions_full[0] is always "none" (no predecessor) and
    # transitions_full[k] (k>=1) is reel["transitions"][k-1].
    transitions_full = [{"type": "none", "duration": 0.0}] + reel["transitions"]

    seg_paths = []
    cue_offset = 0
    for i, seg in enumerate(segments):
        clip = store.get_clip(project, seg["clip_id"])
        start, end = _effective_segment_window(clip, seg)

        if fit_mode == "fit_blur":
            fit_vf = _fit_blur_vf(config.REEL_W, config.REEL_H, fit_scale)
            vf_extra = ",".join(v for v in (color_vf, fit_vf) if v)
        else:
            crop = faces.vertical_crop_filter(
                clip["info"]["width"], clip["info"]["height"], center, config.REEL_W, config.REEL_H
            )
            vf_extra = ",".join(v for v in (color_vf, crop) if v)

        ass_path = None
        if burn_subs:
            local_overrides, n_cues = _segment_cue_overrides(
                clip, start, end, sub_cfg, cue_overrides, cue_offset
            )
            cue_offset += n_cues
            ass_path = str(work / f"seg_{i:04d}.ass")
            subtitles.write_ass(
                ass_path,
                clip,
                start,
                end,
                sub_cfg,
                (config.REEL_W, config.REEL_H),
                local_overrides,
                speakers=project.get("speakers"),
            )

        fade_in = transitions_full[i]["duration"] if transitions_full[i]["type"] == "fade" else 0.0
        fade_out = 0.0
        if i + 1 < len(segments) and transitions_full[i + 1]["type"] == "fade":
            fade_out = transitions_full[i + 1]["duration"]
        seg_len = max(0.05, end - start)
        if fade_in + fade_out > seg_len:
            scale = seg_len / (fade_in + fade_out)
            fade_in *= scale
            fade_out *= scale

        out = work / f"seg_{i:04d}.mp4"
        render_mod._encode_segment(
            clip["path"],
            start,
            end,
            str(out),
            config.REEL_W,
            config.REEL_H,
            fps,
            None,
            None,
            vf_extra,
            ass_path,
            fade_in,
            fade_out,
            config.RENDER_CRF,
            config.RENDER_PRESET,
        )
        seg_paths.append(str(out))
        log.progress(0.2 + 0.6 * (i + 1) / len(segments))
        log(f"segment {i + 1}/{len(segments)}: {clip['filename']} {start:.1f}-{end:.1f}s")

    seg_paths = render_mod._merge_crossfades(
        seg_paths, transitions_full, work, log, config.RENDER_CRF, config.RENDER_PRESET
    )

    work_out = work / f"reel_{reel_id}_render.mp4"
    if len(seg_paths) == 1:
        Path(seg_paths[0]).replace(work_out)
    else:
        log("Concatenating segments...")
        ffmpeg_utils.concat_segments(seg_paths, str(work_out), work)

    if project.get("audio_enhance"):
        log("Enhancing voice audio...")
        raw_wav = work / f"reel_{reel_id}_audio.wav"
        enhanced_wav = work / f"reel_{reel_id}_audio_enhanced.wav"
        remuxed = work / f"reel_{reel_id}_remuxed.mp4"
        ffmpeg_utils.extract_wav(str(work_out), str(raw_wav))
        audio_enhance.enhance(str(raw_wav), str(enhanced_wav))
        ffmpeg_utils.mux_audio(str(work_out), str(enhanced_wav), str(remuxed))
        remuxed.replace(work_out)

    # Exported artifact, title-named (spec v5 addendum "export filenames"):
    # settings.export_dir/<project name>/<sanitized reel title>.mp4.
    export_dir = _export_dir_for(project)
    stem = _export_stem_for_reel(reel)
    final = _unique_export_path(export_dir, stem)
    work_out.replace(final)

    total_duration = ffmpeg_utils.clip_info(str(final))["duration"]
    reel["path"] = str(final)
    reel["status"] = "rendered"
    reel["rendered_at"] = time.strftime("%H:%M:%S")
    reel["duration"] = round(total_duration, 1)
    store.save(project)
    log(f"Done: {final.name} -> {export_dir}")
