"""Stage 7 — Reels: propose ~20 short-form candidates from the kept content,
scored by the local LLM on the transcript (hook / clarity / payoff). Rendering
a candidate crops to 9:16 centered on the speaker's face and burns subtitles
built from whisper word timestamps.

Reel Editor overrides (spec v5): each reel may carry in_override/out_override
(clip-local seconds, may extend beyond the AI window, clamped to clip
bounds), crop_x (0..1 horizontal center, bypasses face detection),
cue_overrides ({cue_index: text}), subtitle_style (partial override merged
over project["subtitles"]), and editable title/description — all honored by
render_reel via _effective_window/_effective_crop_center/_effective_subtitle_cfg.

Export naming (spec v5 addendum): rendered reels are written straight to
settings.export_dir/<project name>/<sanitized reel title>.mp4 (falling back
to "Reel <rank>" when there's no title yet), deduped against what's already
there ("<stem> (2).mp4", ...). Internal work files (the per-reel .ass/.wav
under <project>/work) keep using the reel id; only the final artifact adopts
the title-based name, and reel["path"] is updated to point at it.

Copywriter integration (spec v5 addendum): after picking the top N, each
reel's title/description/hashtags are generated by the COPYWRITER agent
(cutroom/pipeline/copywriter.py, a parallel deliverable) via copy_for_reel —
imported lazily so this module works whether or not that file has landed
yet. On success it replaces reel_scorer's title; on failure/absence the
scorer's title is kept as a fallback."""

import re
import time
import uuid
from pathlib import Path

from .. import config, ffmpeg_utils, llm, settings, store
from ..agents.agents import get_agent
from . import audio_enhance, faces, filters, subtitles


def _candidate_windows(project: dict) -> list[dict]:
    """Sliding windows of consecutive kept sentences within one clip,
    bounded to REEL_MIN_S..REEL_MAX_S."""
    out = []
    for clip in project["clips"]:
        if clip["role"] != "camera":
            continue
        sents = sorted(
            (s for s in project["sentences"] if s["clip_id"] == clip["id"] and s["kept"]),
            key=lambda s: s["start"],
        )
        for i in range(len(sents)):
            acc, texts = [], []
            for j in range(i, len(sents)):
                if acc and sents[j]["start"] - acc[-1]["end"] > 4.0:
                    break  # big content hole — not one continuous thought
                acc.append(sents[j])
                texts.append(sents[j]["text"])
                dur = acc[-1]["end"] - acc[0]["start"]
                if dur > config.REEL_MAX_S:
                    break
                if dur >= config.REEL_MIN_S:
                    out.append(
                        {
                            "clip_id": clip["id"],
                            "start": acc[0]["start"],
                            "end": acc[-1]["end"],
                            "text": " ".join(texts),
                            "duration": round(dur, 1),
                        }
                    )
                    if dur >= config.REEL_MAX_S * 0.75:
                        break
    # thin out: keep at most ~80 for the LLM pass, longest-first per start point
    seen, thinned = set(), []
    for c in sorted(out, key=lambda c: (c["clip_id"], c["start"], -c["duration"])):
        key = (c["clip_id"], round(c["start"] / 5))
        if key in seen:
            continue
        seen.add(key)
        thinned.append(c)
    return thinned[:80]


def _overlap(a: dict, b: dict) -> float:
    if a["clip_id"] != b["clip_id"]:
        return 0.0
    inter = min(a["end"], b["end"]) - max(a["start"], b["start"])
    union = max(a["end"], b["end"]) - min(a["start"], b["start"])
    return max(0.0, inter) / union


def _hashtags_list(value) -> list[str]:
    """Normalize the copywriter's `hashtags` output into a list of tag
    strings. copywriter.py's CopywriterOutput.hashtags is a single
    space-separated string (e.g. "#Foo #Bar") by schema/spec (flat,
    small-model-friendly output) -- naively doing list(value) on a string
    explodes it character-by-character (real bug found on project
    c7642fc7755e's reel b0996e24: hashtags == ['#','R','u',...]). Split on
    whitespace instead; tolerate a real list/tuple too in case the
    copywriter contract ever changes."""
    if not value:
        return []
    if isinstance(value, str):
        return [t for t in value.split() if t.strip()]
    return [str(t) for t in value if str(t).strip()]


def _copy_for_reel_safe(project: dict, reel: dict) -> dict | None:
    """copy_for_reel(project, reel) -> {"title","description","hashtags"},
    or None if the copywriter module isn't available yet (ImportError, a
    parallel deliverable) or it errored on this reel — callers fall back to
    keeping whatever title/description the reel already has."""
    try:
        from .copywriter import copy_for_reel
    except ImportError:
        return None
    try:
        return copy_for_reel(project, reel)
    except Exception:
        return None


def suggest(log, project: dict) -> None:
    if not project.get("sentences"):
        raise RuntimeError("Run Take analysis first.")
    if not llm.available():
        raise RuntimeError("Ollama is not running — reel scoring needs the local LLM.")

    candidates = _candidate_windows(project)
    if not candidates:
        raise RuntimeError("No candidate windows (need >=15s of continuous kept speech).")
    reel_scorer_agent = get_agent("reel_scorer")
    log(f"Scoring {len(candidates)} candidate windows...")

    scored = []
    for ci, cand in enumerate(candidates):
        prompt = f'Candidate window ({cand["duration"]}s):\n"{cand["text"][:1200]}"'
        try:
            s = reel_scorer_agent.run_sync(prompt).output
            c = dict(cand)
            c["hook"] = float(s.hook)
            c["self_contained"] = float(s.self_contained)
            c["payoff"] = float(s.payoff)
            c["title"] = s.title[:80]
            c["score"] = round(c["hook"] * 1.4 + c["self_contained"] + c["payoff"], 1)
            scored.append(c)
        except Exception as e:
            log(f"candidate {ci}: LLM error, skipping ({e})")
        log.progress(min(0.95, (ci + 1) / len(candidates)))

    # top N with limited mutual overlap
    scored.sort(key=lambda c: -c["score"])
    picked = []
    for c in scored:
        if all(_overlap(c, p) < 0.45 for p in picked):
            picked.append(c)
        if len(picked) >= config.REEL_SUGGESTIONS:
            break

    project["reels"] = [
        {
            "id": uuid.uuid4().hex[:8],
            "rank": i + 1,
            "clip_id": c["clip_id"],
            "start": c["start"],
            "end": c["end"],
            "duration": c["duration"],
            "title": c.get("title", ""),
            "description": "",
            "hashtags": [],
            "score": c["score"],
            "hook": c["hook"],
            "self_contained": c["self_contained"],
            "payoff": c["payoff"],
            "text": c["text"],
            "path": None,
            "status": "suggested",
            # Reel Editor overrides (spec v5) — all optional, unset until a
            # PATCH from the Reel Editor sets one.
            "in_override": None,
            "out_override": None,
            "crop_x": None,
            "cue_overrides": {},
            "subtitle_style": {},
        }
        for i, c in enumerate(picked)
    ]

    log("Writing reel copy (title/description/hashtags)...")
    for reel in project["reels"]:
        copy = _copy_for_reel_safe(project, reel)
        if copy:
            reel["title"] = str(copy.get("title") or reel["title"])[:80]
            reel["description"] = str(copy.get("description") or "")
            reel["hashtags"] = _hashtags_list(copy.get("hashtags"))

    store.save(project)
    log(f"Suggested {len(picked)} reels (from {len(scored)} scored candidates).")


def regenerate_copy(project: dict, reel: dict) -> dict:
    """Re-run the copywriter for one reel, unconditionally overwriting its
    title/description/hashtags (spec: "Regenerate copy" button — this is the
    one explicit path allowed to replace a manually-edited title; nothing
    else touches it after suggest() seeds it). Raises RuntimeError if the
    copywriter module isn't available or errors."""
    copy = _copy_for_reel_safe(project, reel)
    if not copy:
        raise RuntimeError(
            "Copywriter unavailable — cutroom/pipeline/copywriter.py missing or errored."
        )
    reel["title"] = str(copy.get("title") or reel["title"])[:80]
    reel["description"] = str(copy.get("description") or "")
    reel["hashtags"] = _hashtags_list(copy.get("hashtags"))
    return reel


# ---------- export filename sanitization (spec v5 addendum) ----------
# Self-contained here (rather than importing cutroom/pipeline/render.py's
# private helpers) so reels.py has no load-order/edit-conflict coupling to a
# file owned by a different task; the sanitization rules are the same by
# spec, just independently implemented.


def _sanitize_title(name: str) -> str:
    """Filename stem: strip /:\\ and control chars, collapse whitespace."""
    cleaned = re.sub(r'[/:\\\x00-\x1f]', "", name or "")
    cleaned = re.sub(r"\s+", " ", cleaned).strip()
    return cleaned


def _safe_folder_name(name: str) -> str:
    cleaned = re.sub(r'[<>:"/\\|?*\x00-\x1f]', "_", name or "").strip()
    return cleaned or "project"


def _unique_export_path(export_dir: Path, stem: str, ext: str = ".mp4") -> Path:
    """Dedupe an export filename against what's already on disk: "<stem>.mp4",
    then "<stem> (2).mp4", "<stem> (3).mp4", ..."""
    candidate = export_dir / f"{stem}{ext}"
    if not candidate.exists():
        return candidate
    n = 2
    while True:
        candidate = export_dir / f"{stem} ({n}){ext}"
        if not candidate.exists():
            return candidate
        n += 1


def _export_dir_for(project: dict) -> Path:
    """settings.export_dir, per-project subfolder (same layout render.py's
    final render uses)."""
    try:
        raw = settings.load().get("export_dir")
    except Exception:
        raw = None
    root = Path(raw).expanduser() if raw else (Path.home() / "Movies" / "Magic Video Editor")
    d = root / _safe_folder_name(project.get("name") or project["id"])
    d.mkdir(parents=True, exist_ok=True)
    return d


def _export_stem_for_reel(reel: dict) -> str:
    stem = _sanitize_title(reel.get("title") or "")
    return stem or f"Reel {reel['rank']}"


# ---------- override resolution (spec v5 data model) ----------


def _effective_window(clip: dict, reel: dict) -> tuple[float, float]:
    """(start, end) honoring in_override/out_override, clamped to the clip's
    own duration (may EXTEND beyond the AI-suggested window, per spec)."""
    duration = (clip.get("info") or {}).get("duration")
    if not duration or duration <= 0:
        duration = max(reel["end"], reel.get("out_override") or 0.0)

    start = reel.get("in_override")
    start = reel["start"] if start is None else float(start)
    end = reel.get("out_override")
    end = reel["end"] if end is None else float(end)

    start = max(0.0, min(start, duration))
    end = max(start + 0.05, min(end, duration))
    return start, end


def _effective_crop_center(log, clip: dict, reel: dict, start: float, end: float):
    """(x, y) fraction center for the 9:16 crop: an explicit crop_x override
    bypasses face detection entirely (spec); otherwise fall back to
    detecting the speaker's face over the effective window."""
    crop_x = reel.get("crop_x")
    if crop_x is not None:
        center = faces.manual_center(crop_x)
        log(f"Using manual crop_x={crop_x} (face detection bypassed)")
        return center
    log("Analyzing frames for speaker position...")
    center = faces.face_center(clip["path"], start, end)
    log(f"Face center: {center if center else 'not found — using frame center'}")
    return center


def _effective_subtitle_cfg(project: dict, reel: dict) -> dict:
    """project["subtitles"] normalized, then partially overridden by
    reel["subtitle_style"] (spec: "partial override of project['subtitles']"
    scoped to just this reel)."""
    base = subtitles.normalize_config(project.get("subtitles"))
    override = reel.get("subtitle_style") or {}
    return subtitles.normalize_config({**base, **override})


def _ass_for_window(
    clip: dict, start: float, end: float, ass_path: str, cfg: dict, cue_overrides: dict | None
) -> None:
    subtitles.write_ass(
        ass_path, clip, start, end, cfg, (config.REEL_W, config.REEL_H), cue_overrides
    )


def render_reel(log, project: dict, reel_id: str) -> None:
    reel = next((r for r in project["reels"] if r["id"] == reel_id), None)
    if not reel:
        raise RuntimeError(f"reel {reel_id} not found")
    clip = store.get_clip(project, reel["clip_id"])
    pdir = store.project_dir(project["id"])
    work = pdir / "work"
    work.mkdir(exist_ok=True)

    start, end = _effective_window(clip, reel)

    center = _effective_crop_center(log, clip, reel, start, end)
    log.progress(0.3)

    crop = faces.vertical_crop_filter(
        clip["info"]["width"],
        clip["info"]["height"],
        center,
        config.REEL_W,
        config.REEL_H,
    )
    color_vf = filters.build_vf(project.get("color"))
    vf_extra = ",".join(v for v in (color_vf, crop) if v)

    sub_cfg = _effective_subtitle_cfg(project, reel)
    ass = None
    if ffmpeg_utils.supports_subtitles():
        # Reels have always burned subtitles regardless of the
        # project["subtitles"]["enabled"] toggle (that toggle governs the
        # main/preview render only) — reels only skip burn-in when libass is
        # unavailable, matching the historical behavior this preserves.
        ass = str(work / f"reel_{reel_id}.ass")
        _ass_for_window(clip, start, end, ass, sub_cfg, reel.get("cue_overrides"))
    else:
        log("ffmpeg has no libass — rendering without burned subtitles")

    # Internal work file, id-named (spec: "internal work files keep their ids").
    work_out = work / f"reel_{reel_id}_render.mp4"
    log(f"Rendering {config.REEL_W}x{config.REEL_H} with subtitles...")
    ffmpeg_utils.cut_segment(
        clip["path"],
        start,
        end,
        str(work_out),
        config.REEL_W,
        config.REEL_H,
        min(clip["info"]["fps"] or 30.0, 60.0),
        vf_extra=vf_extra,
        ass_path=ass,
    )

    if project.get("audio_enhance"):
        log("Enhancing voice audio...")
        raw_wav = work / f"reel_{reel_id}_audio.wav"
        enhanced_wav = work / f"reel_{reel_id}_audio_enhanced.wav"
        remuxed = work / f"reel_{reel_id}_remuxed.mp4"
        ffmpeg_utils.extract_wav(str(work_out), str(raw_wav))
        audio_enhance.enhance(str(raw_wav), str(enhanced_wav))
        ffmpeg_utils.mux_audio(str(work_out), str(enhanced_wav), str(remuxed))
        remuxed.replace(work_out)

    # Exported artifact, title-named (spec v5 addendum "export filenames"):
    # settings.export_dir/<project name>/<sanitized reel title>.mp4.
    export_dir = _export_dir_for(project)
    stem = _export_stem_for_reel(reel)
    final = _unique_export_path(export_dir, stem)
    work_out.replace(final)

    reel["path"] = str(final)
    reel["status"] = "rendered"
    reel["rendered_at"] = time.strftime("%H:%M:%S")
    reel["duration"] = round(end - start, 1)
    store.save(project)
    log(f"Done: {final.name} -> {export_dir}")
